AST Validatation
isidentical/cpython pull request #1
Opened 2020-10-29 15:51 UTC by isidentical

2020-10-29 16:00 UTC, isidentical commented on Python/ast.c
> +    int op, left, right;
Declarations inside of case's are a bit problematic (definitions aren't statements in C). So, we can either extract some cases into their own functions (just like `validate_pattern_attribute`) to limit these definitions to where they needed, or keep it like this.

2021-02-09 17:00 UTC, isidentical commented
CC: @brandtbucher

2021-02-09 18:35 UTC, brandtbucher commented on Python/ast.c
> +    int op, left, right;
Yeah, this is fine. FYI, other options I've used before include adding a semicolon at the beginning of the problematic cases:

```c
case whatever:;  // <- Note this semicolon.
    // Declarations valid here.
```

Or wrapping them in brackets (which I prefer for readability):

```c
case whatever: {
    // Declarations valid here.
}
```

2021-02-09 18:52 UTC, brandtbucher commented on Python/ast.c
> +                if (keyword->arg == Py_None) {
I believe this will be `NULL` for `**kwargs`, not `None`:

```suggestion
                if (!keyword->arg) {
```

2021-02-09 19:08 UTC, brandtbucher commented on Python/ast.c
> +                }
```suggestion
                PyErr_SetString(PyExc_ValueError,
                                "only numbers are allowed as an operand "
                                "to UnaryOp nodes inside of a pattern");
                return 0;
```

2021-02-09 19:18 UTC, brandtbucher commented on Python/ast.c
> +                    }
This is a bit more readable for me:

```suggestion
                    if (element->v.Starred.value->kind != Name_kind) {
                        PyErr_SetString(PyExc_ValueError,
                                        "the single star pattern's target can "
                                        "only be Name");
                        return 0;
                    }
                    if (!validate_expr(element->v.Starred.value, Store)) {
                        return 0;
                    }
```

2021-02-09 19:22 UTC, brandtbucher commented on Python/ast.c
> +                         key->kind == BinOp_kind) {
```suggestion
                         key->kind == BinOp_kind ||
                         key->kind == UnaryOp_kind) {
```

2021-02-09 19:32 UTC, brandtbucher commented on Python/ast.c
> +            return 0;
Need to validate the actual name as well:

```suggestion
            return validate_expr(pattern, Store));
```

2021-02-09 19:33 UTC, brandtbucher commented on Python/ast.c
> +                    }
This is a bit more readable for me:
```suggestion
                    if (value->kind != Name_kind) {
                        PyErr_SetString(PyExc_ValueError,
                                        "the double star pattern's target can "
                                        "only be Name");
                        return 0;
                    }
                    if (!validate_expr(value, Store)) {
                        return 0;
                    }
```

2021-02-09 19:35 UTC, brandtbucher commented on Python/ast.c
> +                    // The position of **rest is handled on the compiler
We assert the position (if present), but not the quantity. So I think we need to add a check to raise if there are two or more starred patterns.

2021-02-09 19:39 UTC, brandtbucher requested changes
Great work on this (and thanks for your patience). I've left some comments.

2021-02-12 15:42 UTC, isidentical commented
Thanks @brandtbucher!

2021-06-24 08:27 UTC, closed without merging